### PR TITLE
Merge opencog/atomspace to singnet/atomspace

### PR DESCRIPTION
**Pull request by ngeiswei**
Contains:
- Free commits https://github.com/singnet/atomspace/commit/ea8225ac3bbad8a2bfaaf4a6a4b360676b71b8de to https://github.com/singnet/atomspace/commit/33c2023679652ada933527d7e165284eab0509b2
- PR https://github.com/opencog/atomspace/pull/2250
- PR https://github.com/opencog/atomspace/pull/2251
- PR https://github.com/opencog/atomspace/pull/2252
- PR https://github.com/opencog/atomspace/pull/2253
- PR https://github.com/opencog/atomspace/pull/2254
- PR https://github.com/opencog/atomspace/pull/2255
- PR https://github.com/opencog/atomspace/pull/2256
- PR https://github.com/opencog/atomspace/pull/2257
- PR https://github.com/opencog/atomspace/pull/2258
- PR https://github.com/opencog/atomspace/pull/2259
- PR https://github.com/opencog/atomspace/pull/2260
- PR https://github.com/opencog/atomspace/pull/2262
- PR https://github.com/opencog/atomspace/pull/2263
- PR https://github.com/opencog/atomspace/pull/2264
- PR https://github.com/opencog/atomspace/pull/2265
- PR https://github.com/opencog/atomspace/pull/2266
- PR https://github.com/opencog/atomspace/pull/2268
- PR https://github.com/opencog/atomspace/pull/2269

### CODE REVIEW

**Comment by ngeiswei** [comment]
circleci is stuck on opencog...

**Comment by ngeiswei** [comment]
@vsbogd unless you see something wrong with that PR (as well as `singnet/opencog`'s) I'd like to merge it (as to be able to start running ure checks on the singnet side).

**Comment by vsbogd** [comment]
Hi @ngeiswei , sorry for late response, couple of questions/suggestsions on this:
1. I suggest tagging current `singnet/xxx` version each time before merging changes from `opencog/xxx`: (a) it will help to rollback changes if something goes wrong; (b) it makes possible to stick to the old stable version;
2. I am a bit afraid of last merges to `opencog/atomspace` for me it looks like it is still not stable; this risk is mitigated by item (1) obviously; are you sure that it is at same stable point now?
3. Do you know why URE build is red here?

**Comment by vsbogd** [comment]
@ngeiswei, I think it is better to close it before https://github.com/opencog/atomspace/issues/2281 is fixed

**Comment by ngeiswei** [comment]
Yeah, and there's been so many changes, better close it and start again.

**Pull request closed without merging**
