### PR TITLE
Update cmake configuration for disabling builds against python 3

### PR DESCRIPTION
**Pull request by AmeBel**
To use Python2 only from the build directory run the following 
` rm CMakeCache.txt && cmake -DCMAKE_DISABLE_FIND_PACKAGE_Python3Interp=TRUE ..`

### CODE REVIEW

**Comment by ferrouswheel** [comment]
This forces people to use Python 3.4 because you've changed to explicitly calling `nosetests-3.4` :-(

The cmake variable to disable Python 3 detection could also be better named (unless this is an inbuilt variable provided by CMake), and probably should be added to the build documentation.

**Comment by AmeBel** [comment]
Installing using pip3, nose executable is called `nosetests-3.4` not `nosetests3`. 

It is [inbuilt](https://cmake.org/cmake/help/v3.5/variable/CMAKE_DISABLE_FIND_PACKAGE_PackageName.html).

Done https://wiki.opencog.org/w/Building_OpenCog#Building

**Comment by AmeBel** [comment]
I had tested against python 3.5.2 in ubuntu 16.04 container, and just tested against python 3.6.5 in ubuntu 18.04 container, & python 3.6.6 in conda, in all cases it is `nosetests-3.4`. Is there some option in pip that gets(or renames) `nosetest-3.5/3.6`?

**Comment by ferrouswheel** [comment]
Wow, I just checked on an Ubuntu 16.04 box and even though I'm installing nose 1.3.7 with python 3.5 it still calls it nosetests-3.4!

I found this issue nose-devs/nose#1009 but it's from 2016... so I guess it isn't going to change any time soon.

**Comment by vsbogd** [comment]
I don't have nosetests-3.4 and have nosetests3 instead probably because I don't use pip, just installed python3-nose in Ubuntu 18.

**Comment by vsbogd** [comment]
I see that [README.md](https://github.com/singnet/atomspace/blob/master/README.md) doesn't describe how to install python to build Atomspace properly. I think it makes sense add this information to the documentation.

**Pull request merged**
