### PR TITLE
remove atomspace creation in get_default_atomspace

### LINKED ISSUE #154: get_default_atomspace returns atomspace which is not default
steps to reproduce:

```
>>> from opencog.type_constructors import *
>>> from opencog.utilities import get_default_atomspace
>>> at = get_default_atomspace()
>>> ConceptNode("test")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "core_types.pyx", line 17, in opencog.type_constructors.ConceptNode
  File "utilities.pyx", line 84, in opencog.utilities.add_node
RuntimeError: current atomspace is not set
>>> at
<opencog.atomspace.AtomSpace object at 0x7fae062877c0>
```

### PR DESCRIPTION
**Pull request by noskill**
nullpointer was passed to AtomSpace_factory
fixes  #154

### CODE REVIEW

**Comment by noskill** [comment]
@vsbogd Could you please review the changes

**Comment by ngeiswei** [comment]
@noskill, maybe such PR could go to opencog/atomspace instead?  I doubt Linas would reject it.   Generally speaking I would recommend to apply changes upstream when possible, as it may slow down the growth of conflict rate when merging opencog/atomspace to singnet/atomspace (which I still regularly do for rocca).

If you agree I would let you take care of it, but if you're too busy I can handle it, just let me know.

**Comment by noskill** [comment]
@ngeiswei ok, I'll make PR to the opencog/atomspace

**Comment by noskill** [comment]
@ngeiswei https://github.com/opencog/atomspace/pull/2808

**Pull request merged**
