### PR TITLE
Merge opencog to singnet

### PR DESCRIPTION
**Pull request by vsbogd**

### CODE REVIEW

**Comment by vsbogd** [comment]
@AmeBel, could you please help: I don't understand why this PR cannot be merged? What does "Waiting for status to be reported" mean?

**Comment by AmeBel** [comment]
looking into it

**Comment by AmeBel** [comment]
The issue that blocked the merge was that @ngeiswei had changed the configuration for branch protection on github 9 days ago.

There are 3 circleci checks that run on this repo.
A. atomspace build & test
B. opencog build & test
C. packaging which does caching of results and restricted to occur on master branch only.

A & B were enabled as required checks that must pass on every pr before merge. Nil disabled that, and enabled C as the required checks for the pr. Since C only runs on master branch and prs are not master thus merging was disabled. I have reverted that change.

**Comment by AmeBel** [comment]
@ngeiswei you had enabled the branch protection
> Require branches to be up to date before merging
This ensures pull requests targeting a matching branch have been tested with the latest code.

Enabling this means every open pr have to merge master or rebase on master when their is a change on master. Are you sure you want to do that? 

I have disabled that for the moment.

**Comment by ngeiswei** [comment]
Thanks @AmeBel , no I don't particularly want that, it was just a mistake on my part.

**Comment by vsbogd** [comment]
Thanks @AmeBel !

**Pull request merged**
