### PR TITLE
GroundedPredicate binding for Haskell

### PR DESCRIPTION
**Pull request by Necr0x0Der**
[comments](https://github.com/singnet/atomspace/pull/21)

### CODE REVIEW

**Comment by rTreutlein** [comment]
The code looks fine. But is there anybody that actually needs this?

**Comment by ngeiswei** [comment]
I'm merging based on trust.

**Comment by Necr0x0Der** [comment]
Thanks, @ngeiswei and @rTreutlein .

**Comment by ngeiswei** [comment]
BTW, if the Haskell bindings are complete enough I would be happy to switch to Haskell. But I suppose the URE, the Logger, and some other components are not ported for it. Maybe I should do it myself, when I don't have something more urgent to do...

**Pull request merged**
